name: Conditional env variable

on: workflow_dispatch

env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: "echo"
        run: echo "Hello ${{ env.env_var }}"